use_frameworks!

platform :ios, '13.5'

source 'https://github.com/touchlab/PublicPodspecs.git'

target 'KaMPKitiOS' do
    if ENV.include?("LOCAL_KOTLIN_PATH")
      pod 'shared', :path => ENV["LOCAL_KOTLIN_PATH"]
    else
      pod 'shared', '~> 1.2.0'
    end
    pod 'SwiftLint'
end
